"""added salon table and relationship

Revision ID: 5b4bec0510af
Revises: beec64c9fc8d
Create Date: 2023-03-27 17:06:16.441064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b4bec0510af'
down_revision = 'beec64c9fc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aula', sa.String(length=20), nullable=True),
    sa.Column('horaEntrada', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idaula', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'salon', ['idaula'], ['id'])
        batch_op.drop_column('aula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aula', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idaula')

    op.drop_table('salon')
    # ### end Alembic commands ###
